package dto;

import pojo.Paciente;

public class RSRegistroPaciente {
    private boolean error;
    private String mensaje;
    private String nip; // Autogenerated NIP returned by the API
    private Object valor; // Fallback from API's generic Respuesta
    private Paciente paciente;

    public RSRegistroPaciente() {}

    public boolean isError() { return error; }
    public void setError(boolean error) { this.error = error; }

    public String getMensaje() { return mensaje; }
    public void setMensaje(String mensaje) { this.mensaje = mensaje; }

    public String getNip() { return nip; }
    public void setNip(String nip) { this.nip = nip; }

    public Object getValor() { return valor; }
    public void setValor(Object valor) { this.valor = valor; }

    public Paciente getPaciente() { return paciente; }
    public void setPaciente(Paciente paciente) { this.paciente = paciente; }
}
